import { AnomalyDetection, SurveyRecord, DashboardMetrics } from '@/types';

export const SONAR_CLASSES = [
  'Shipwreck / Vessel Hull',
  'Ghost Net / Trawl Gear',
  'Subsea Pipeline Segment',
  'Exposed Telecomm Cable',
  'Naval Mine / UXO Hazard',
  'Anchor & Chain Snag',
  'Shipping Container (Lost Cargo)',
  'Aircraft Debris / Fuselage',
  'Marine Turbine / Foundation',
  'Concrete Mattress / Scour Protection',
  'Dredging Spoil Pile',
  'Benthic Reef Structure',
  'Pockmark / Methane Seep',
  'Submarine Wellhead',
  'Discarded Drum / Chemical Hazard',
  'Boulder Field / Navigational Shoal',
  'Unknown Acoustic Anomaly',
] as const;

export const INITIAL_SURVEYS: SurveyRecord[] = [
  {
    id: 'SURV-2026-NIOT-088',
    title: 'Bay of Bengal Deepwater Corridor Alpha-4',
    filename: 'NIOT_SAS_20260824_Pass03_swath100m.raw',
    imageUrl: 'procedural:pass03',
    uploaded_at: '2026-08-30T14:22:10Z',
    status: 'COMPLETED',
    progress_pct: 100,
    total_anomalies: 6,
    critical_count: 2,
    high_count: 2,
    medium_count: 1,
    low_count: 1,
    metadata: {
      vessel_name: 'ORV Sagar Nidhi (NIOT)',
      sonar_frequency_khz: 455,
      swath_range_m: 100,
      resolution_m_px: 0.05,
      altitude_m: 12.5,
      heading_deg: 42.5,
      start_coords: [13.0827, 80.3128],
      end_coords: [13.1492, 80.3784],
      area_coverage_km2: 14.8,
      water_depth_m: 64.2,
      sound_velocity_mps: 1512.4,
      mode: 'Ping Header Metadata',
      model_version: 'YOLOv8s-Sonar v2.1-NIOT',
    },
    stages: [
      { id: 'INGESTION', name: 'Raw Acoustic Ingestion', description: 'Dual-channel demodulation & slant-range correction', status: 'completed', elapsed_ms: 142 },
      { id: 'DENOISE', name: 'Adaptive Speckle Denoise', description: 'Lee-Sigma filtering & TV regularization', status: 'completed', elapsed_ms: 380 },
      { id: 'INFERENCE', name: 'YOLOv8s Inference', description: 'Multi-scale acoustic backscatter feature extraction', status: 'completed', elapsed_ms: 520 },
      { id: 'MC_DROPOUT', name: 'MC-Dropout Uncertainty', description: '10-pass stochastic forward sampling (±σ)', status: 'completed', elapsed_ms: 410 },
      { id: 'SHADOW_SIZING', name: 'Acoustic Shadow Sizing', description: 'Trigonometric target height estimation from nadir', status: 'completed', elapsed_ms: 290 },
      { id: 'GEOTAGGING', name: 'Hydrographic Geotagging', description: 'WGS84 ellipsoid projection & layback transform', status: 'completed', elapsed_ms: 180 },
    ],
    detections: [
      {
        id: 'HAZ-2026-001',
        class_name: 'Shipwreck / Vessel Hull',
        class_id: 0,
        confidence_pct: 94.2,
        uncertainty_std: 0.024,
        certainty: 'high',
        bbox_px: [240, 310, 190, 85],
        dimensions_m: { length: 18.4, width: 4.2, height: 2.8 },
        location: { lat: 13.094215, lon: 80.324891, geo_confidence: 'measured' },
        risk: 'CRITICAL',
        has_shadow: true,
        shadow_vector: { startX: 430, startY: 350, endX: 525, endY: 362, length_m: 6.8, estimated_height_m: 2.8 },
        channel: 'port',
        ping_index: 1240,
        slant_range_m: 38.4,
        diver_recovery_flagged: true,
        survey_id: 'SURV-2026-NIOT-088',
        detected_at: '2026-08-30T14:24:00Z',
        notes: 'Inverted steel hull with structural deformation. Prominent acoustic shadow indicating 2.8m relief above seabed.',
      },
      {
        id: 'HAZ-2026-002',
        class_name: 'Ghost Net / Trawl Gear',
        class_id: 1,
        confidence_pct: 88.6,
        uncertainty_std: 0.038,
        certainty: 'high',
        bbox_px: [520, 580, 130, 95],
        dimensions_m: { length: 12.8, width: 8.5, height: 1.4 },
        location: { lat: 13.101844, lon: 80.332104, geo_confidence: 'measured' },
        risk: 'HIGH',
        has_shadow: true,
        shadow_vector: { startX: 650, startY: 625, endX: 710, endY: 635, length_m: 4.1, estimated_height_m: 1.4 },
        channel: 'starboard',
        ping_index: 2310,
        slant_range_m: 62.1,
        diver_recovery_flagged: true,
        survey_id: 'SURV-2026-NIOT-088',
        detected_at: '2026-08-30T14:25:12Z',
        notes: 'Dense synthetic monofilament clump tangled over rocky outcrop. Significant navigation snag hazard.',
      },
      {
        id: 'HAZ-2026-003',
        class_name: 'Subsea Pipeline Segment',
        class_id: 2,
        confidence_pct: 96.1,
        uncertainty_std: 0.015,
        certainty: 'high',
        bbox_px: [80, 840, 420, 45],
        dimensions_m: { length: 44.0, width: 1.2, height: 0.9 },
        location: { lat: 13.112903, lon: 80.341852, geo_confidence: 'measured' },
        risk: 'HIGH',
        has_shadow: true,
        shadow_vector: { startX: 500, startY: 860, endX: 545, endY: 865, length_m: 2.9, estimated_height_m: 0.9 },
        channel: 'port',
        ping_index: 3360,
        slant_range_m: 28.5,
        diver_recovery_flagged: false,
        survey_id: 'SURV-2026-NIOT-088',
        detected_at: '2026-08-30T14:26:45Z',
        notes: 'Unburied crude transport pipeline segment showing free-span exposure over 18m trough.',
      },
      {
        id: 'HAZ-2026-004',
        class_name: 'Naval Mine / UXO Hazard',
        class_id: 4,
        confidence_pct: 79.4,
        uncertainty_std: 0.052,
        certainty: 'moderate',
        bbox_px: [610, 1120, 65, 60],
        dimensions_m: { length: 2.1, width: 1.9, height: 1.1 },
        location: { lat: 13.125190, lon: 80.354021, geo_confidence: 'estimated' },
        risk: 'CRITICAL',
        has_shadow: true,
        shadow_vector: { startX: 675, startY: 1150, endX: 720, endY: 1155, length_m: 3.2, estimated_height_m: 1.1 },
        channel: 'starboard',
        ping_index: 4480,
        slant_range_m: 74.0,
        diver_recovery_flagged: true,
        survey_id: 'SURV-2026-NIOT-088',
        detected_at: '2026-08-30T14:28:10Z',
        notes: 'Spherical metallic signature with mooring cable shadow artifact. Defense ordnance clearance recommended.',
      },
      {
        id: 'HAZ-2026-005',
        class_name: 'Shipping Container (Lost Cargo)',
        class_id: 6,
        confidence_pct: 91.8,
        uncertainty_std: 0.021,
        certainty: 'high',
        bbox_px: [290, 1420, 160, 70],
        dimensions_m: { length: 12.2, width: 2.4, height: 2.6 },
        location: { lat: 13.136450, lon: 80.365112, geo_confidence: 'measured' },
        risk: 'MEDIUM',
        has_shadow: true,
        shadow_vector: { startX: 450, startY: 1455, endX: 535, endY: 1460, length_m: 5.6, estimated_height_m: 2.6 },
        channel: 'port',
        ping_index: 5680,
        slant_range_m: 45.2,
        diver_recovery_flagged: false,
        survey_id: 'SURV-2026-NIOT-088',
        detected_at: '2026-08-30T14:30:20Z',
        notes: 'Standard 40ft intermodal container lying upright on sediment. Corroded corners.',
      },
      {
        id: 'HAZ-2026-006',
        class_name: 'Boulder Field / Navigational Shoal',
        class_id: 15,
        confidence_pct: 84.3,
        uncertainty_std: 0.033,
        certainty: 'high',
        bbox_px: [560, 1720, 180, 110],
        dimensions_m: { length: 16.5, width: 11.0, height: 1.8 },
        location: { lat: 13.144810, lon: 80.374201, geo_confidence: 'measured' },
        risk: 'LOW',
        has_shadow: true,
        shadow_vector: { startX: 740, startY: 1775, endX: 790, endY: 1782, length_m: 3.5, estimated_height_m: 1.8 },
        channel: 'starboard',
        ping_index: 6890,
        slant_range_m: 81.3,
        diver_recovery_flagged: false,
        survey_id: 'SURV-2026-NIOT-088',
        detected_at: '2026-08-30T14:32:00Z',
        notes: 'Dense cluster of igneous granite boulders forming bathymetric ridge.',
      },
    ],
  },
  {
    id: 'SURV-2026-CHENN-104',
    title: 'Chennai Port Outer Anchorage Shoal Inspection',
    filename: 'CHENN_PORT_SSS_Pass01_HighRes.raw',
    imageUrl: 'procedural:pass01',
    uploaded_at: '2026-08-29T11:05:40Z',
    status: 'COMPLETED',
    progress_pct: 100,
    total_anomalies: 4,
    critical_count: 1,
    high_count: 2,
    medium_count: 1,
    low_count: 0,
    metadata: {
      vessel_name: 'RV Sagar Paschimi',
      sonar_frequency_khz: 900,
      swath_range_m: 75,
      resolution_m_px: 0.03,
      altitude_m: 9.8,
      heading_deg: 118.0,
      start_coords: [13.0645, 80.2988],
      end_coords: [13.0910, 80.3340],
      area_coverage_km2: 8.4,
      water_depth_m: 28.5,
      sound_velocity_mps: 1518.0,
      mode: 'Ping Header Metadata',
      model_version: 'YOLOv8s-Sonar v2.1-NIOT',
    },
    stages: [
      { id: 'INGESTION', name: 'Raw Acoustic Ingestion', description: 'Completed', status: 'completed', elapsed_ms: 120 },
      { id: 'DENOISE', name: 'Adaptive Speckle Denoise', description: 'Completed', status: 'completed', elapsed_ms: 290 },
      { id: 'INFERENCE', name: 'YOLOv8s Inference', description: 'Completed', status: 'completed', elapsed_ms: 450 },
      { id: 'MC_DROPOUT', name: 'MC-Dropout Uncertainty', description: 'Completed', status: 'completed', elapsed_ms: 380 },
      { id: 'SHADOW_SIZING', name: 'Acoustic Shadow Sizing', description: 'Completed', status: 'completed', elapsed_ms: 240 },
      { id: 'GEOTAGGING', name: 'Hydrographic Geotagging', description: 'Completed', status: 'completed', elapsed_ms: 150 },
    ],
    detections: [
      {
        id: 'HAZ-2026-011',
        class_name: 'Anchor & Chain Snag',
        class_id: 5,
        confidence_pct: 92.5,
        uncertainty_std: 0.019,
        certainty: 'high',
        bbox_px: [310, 420, 110, 80],
        dimensions_m: { length: 6.4, width: 3.8, height: 1.9 },
        location: { lat: 13.072110, lon: 80.309450, geo_confidence: 'measured' },
        risk: 'CRITICAL',
        has_shadow: true,
        shadow_vector: { startX: 420, startY: 460, endX: 475, endY: 465, length_m: 4.2, estimated_height_m: 1.9 },
        channel: 'port',
        ping_index: 1680,
        slant_range_m: 32.0,
        diver_recovery_flagged: true,
        survey_id: 'SURV-2026-CHENN-104',
        detected_at: '2026-08-29T11:08:12Z',
      },
      {
        id: 'HAZ-2026-012',
        class_name: 'Ghost Net / Trawl Gear',
        class_id: 1,
        confidence_pct: 87.2,
        uncertainty_std: 0.041,
        certainty: 'high',
        bbox_px: [540, 790, 140, 90],
        dimensions_m: { length: 14.2, width: 7.6, height: 1.2 },
        location: { lat: 13.080550, lon: 80.318900, geo_confidence: 'measured' },
        risk: 'HIGH',
        has_shadow: true,
        shadow_vector: { startX: 680, startY: 835, endX: 730, endY: 840, length_m: 3.4, estimated_height_m: 1.2 },
        channel: 'starboard',
        ping_index: 3160,
        slant_range_m: 54.8,
        diver_recovery_flagged: true,
        survey_id: 'SURV-2026-CHENN-104',
        detected_at: '2026-08-29T11:10:45Z',
      },
      {
        id: 'HAZ-2026-013',
        class_name: 'Exposed Telecomm Cable',
        class_id: 3,
        confidence_pct: 90.1,
        uncertainty_std: 0.027,
        certainty: 'high',
        bbox_px: [120, 1150, 360, 35],
        dimensions_m: { length: 38.0, width: 0.4, height: 0.3 },
        location: { lat: 13.086400, lon: 80.327600, geo_confidence: 'measured' },
        risk: 'HIGH',
        has_shadow: false,
        channel: 'port',
        ping_index: 4600,
        slant_range_m: 22.4,
        diver_recovery_flagged: false,
        survey_id: 'SURV-2026-CHENN-104',
        detected_at: '2026-08-29T11:12:30Z',
      },
      {
        id: 'HAZ-2026-014',
        class_name: 'Concrete Mattress / Scour Protection',
        class_id: 9,
        confidence_pct: 86.4,
        uncertainty_std: 0.035,
        certainty: 'high',
        bbox_px: [490, 1530, 160, 120],
        dimensions_m: { length: 9.6, width: 6.0, height: 0.8 },
        location: { lat: 13.089900, lon: 80.332100, geo_confidence: 'estimated' },
        risk: 'MEDIUM',
        has_shadow: true,
        shadow_vector: { startX: 650, startY: 1590, endX: 690, endY: 1595, length_m: 2.6, estimated_height_m: 0.8 },
        channel: 'starboard',
        ping_index: 6120,
        slant_range_m: 48.0,
        diver_recovery_flagged: false,
        survey_id: 'SURV-2026-CHENN-104',
        detected_at: '2026-08-29T11:15:00Z',
      },
    ],
  },
  {
    id: 'SURV-2026-ANDMN-042',
    title: 'Andaman Sea Trench Subsea Hazard Mapping',
    filename: 'ANDAMAN_TRANSECT_09B_SAS.raw',
    imageUrl: 'procedural:pass02',
    uploaded_at: '2026-08-27T08:14:22Z',
    status: 'COMPLETED',
    progress_pct: 100,
    total_anomalies: 5,
    critical_count: 2,
    high_count: 1,
    medium_count: 1,
    low_count: 1,
    metadata: {
      vessel_name: 'INS Makar (Hydrographic Dept)',
      sonar_frequency_khz: 410,
      swath_range_m: 120,
      resolution_m_px: 0.06,
      altitude_m: 16.0,
      heading_deg: 215.4,
      start_coords: [11.6234, 92.7265],
      end_coords: [11.5540, 92.6820],
      area_coverage_km2: 26.5,
      water_depth_m: 142.0,
      sound_velocity_mps: 1508.5,
      mode: 'Ping Header Metadata',
      model_version: 'YOLOv8s-Sonar v2.1-NIOT',
    },
    stages: [
      { id: 'INGESTION', name: 'Raw Acoustic Ingestion', description: 'Completed', status: 'completed', elapsed_ms: 160 },
      { id: 'DENOISE', name: 'Adaptive Speckle Denoise', description: 'Completed', status: 'completed', elapsed_ms: 340 },
      { id: 'INFERENCE', name: 'YOLOv8s Inference', description: 'Completed', status: 'completed', elapsed_ms: 510 },
      { id: 'MC_DROPOUT', name: 'MC-Dropout Uncertainty', description: 'Completed', status: 'completed', elapsed_ms: 430 },
      { id: 'SHADOW_SIZING', name: 'Acoustic Shadow Sizing', description: 'Completed', status: 'completed', elapsed_ms: 280 },
      { id: 'GEOTAGGING', name: 'Hydrographic Geotagging', description: 'Completed', status: 'completed', elapsed_ms: 190 },
    ],
    detections: [
      {
        id: 'HAZ-2026-021',
        class_name: 'Shipwreck / Vessel Hull',
        class_id: 0,
        confidence_pct: 95.8,
        uncertainty_std: 0.016,
        certainty: 'high',
        bbox_px: [210, 480, 240, 110],
        dimensions_m: { length: 32.5, width: 7.8, height: 4.6 },
        location: { lat: 11.605400, lon: 92.714200, geo_confidence: 'measured' },
        risk: 'CRITICAL',
        has_shadow: true,
        shadow_vector: { startX: 450, startY: 535, endX: 580, endY: 550, length_m: 9.8, estimated_height_m: 4.6 },
        channel: 'port',
        ping_index: 1920,
        slant_range_m: 42.0,
        diver_recovery_flagged: true,
        survey_id: 'SURV-2026-ANDMN-042',
        detected_at: '2026-08-27T08:18:00Z',
      },
      {
        id: 'HAZ-2026-022',
        class_name: 'Aircraft Debris / Fuselage',
        class_id: 7,
        confidence_pct: 82.7,
        uncertainty_std: 0.046,
        certainty: 'moderate',
        bbox_px: [560, 920, 140, 85],
        dimensions_m: { length: 11.2, width: 4.5, height: 2.1 },
        location: { lat: 11.589100, lon: 92.703100, geo_confidence: 'estimated' },
        risk: 'CRITICAL',
        has_shadow: true,
        shadow_vector: { startX: 700, startY: 962, endX: 760, endY: 970, length_m: 5.2, estimated_height_m: 2.1 },
        channel: 'starboard',
        ping_index: 3680,
        slant_range_m: 68.4,
        diver_recovery_flagged: true,
        survey_id: 'SURV-2026-ANDMN-042',
        detected_at: '2026-08-27T08:21:30Z',
      },
      {
        id: 'HAZ-2026-023',
        class_name: 'Ghost Net / Trawl Gear',
        class_id: 1,
        confidence_pct: 89.4,
        uncertainty_std: 0.034,
        certainty: 'high',
        bbox_px: [340, 1310, 120, 80],
        dimensions_m: { length: 15.0, width: 9.0, height: 1.6 },
        location: { lat: 11.572400, lon: 92.693400, geo_confidence: 'measured' },
        risk: 'HIGH',
        has_shadow: true,
        shadow_vector: { startX: 460, startY: 1350, endX: 510, endY: 1355, length_m: 3.8, estimated_height_m: 1.6 },
        channel: 'port',
        ping_index: 5240,
        slant_range_m: 36.5,
        diver_recovery_flagged: true,
        survey_id: 'SURV-2026-ANDMN-042',
        detected_at: '2026-08-27T08:24:10Z',
      },
      {
        id: 'HAZ-2026-024',
        class_name: 'Pockmark / Methane Seep',
        class_id: 12,
        confidence_pct: 91.2,
        uncertainty_std: 0.022,
        certainty: 'high',
        bbox_px: [510, 1620, 190, 130],
        dimensions_m: { length: 22.0, width: 18.0, height: null },
        location: { lat: 11.561000, lon: 92.686000, geo_confidence: 'measured' },
        risk: 'MEDIUM',
        has_shadow: false,
        channel: 'starboard',
        ping_index: 6480,
        slant_range_m: 60.0,
        diver_recovery_flagged: false,
        survey_id: 'SURV-2026-ANDMN-042',
        detected_at: '2026-08-27T08:26:45Z',
      },
      {
        id: 'HAZ-2026-025',
        class_name: 'Discarded Drum / Chemical Hazard',
        class_id: 14,
        confidence_pct: 77.8,
        uncertainty_std: 0.058,
        certainty: 'moderate',
        bbox_px: [280, 1890, 60, 50],
        dimensions_m: { length: 1.2, width: 0.9, height: 0.8 },
        location: { lat: 11.555200, lon: 92.682500, geo_confidence: 'estimated' },
        risk: 'LOW',
        has_shadow: true,
        shadow_vector: { startX: 340, startY: 1915, endX: 375, endY: 1918, length_m: 2.1, estimated_height_m: 0.8 },
        channel: 'port',
        ping_index: 7560,
        slant_range_m: 30.2,
        diver_recovery_flagged: false,
        survey_id: 'SURV-2026-ANDMN-042',
        detected_at: '2026-08-27T08:28:50Z',
      },
    ],
  },
];

export const INITIAL_METRICS: DashboardMetrics = {
  totalSeabedScannedKm2: 1842.6,
  scanRateSparkline: [24.2, 28.5, 31.0, 27.8, 35.4, 38.2, 42.1, 40.8, 45.6, 49.2, 52.0, 56.4],
  confirmedHazardsTotal: 47,
  hazardsBreakdown: {
    critical: 12,
    infrastructure: 18,
    minor: 17,
  },
  modelConfidenceAvg: 89.7,
  modelConfidenceStd: 0.038,
  ghostNetClusters: 3,
  recentAnomalies: [
    INITIAL_SURVEYS[0].detections[0],
    INITIAL_SURVEYS[0].detections[1],
    INITIAL_SURVEYS[0].detections[3],
    INITIAL_SURVEYS[1].detections[0],
    INITIAL_SURVEYS[2].detections[0],
    INITIAL_SURVEYS[2].detections[1],
  ],
  recentSurveys: INITIAL_SURVEYS,
};
